### ISSUE TITLE
update statistics

### ISSUE THREAD

**Issue by erdos** [erdos/uclj#17]
thanks to the excellent work put in bb, latest versions perform much better!
```
[erdos@fedora uclj]$ bb --version
babashka v0.8.157
[erdos@fedora uclj]$ bb ./benchmark.clj
| test case  | uclj       | bb         | clojure
| day1.clj   | 44+1       | 37+2       | 929+26
| day2.clj   | 63+2       | 40+1       | 1045+43
| day3.clj   | 98+2       | 98+4       | 1151+34
| day4.clj   | 242+10     | 245+9      | 1133+40
| day5.clj   | 5107+139   | 5394+166   | 2728+83
| day6.clj   | 35+3       | 14+1       | 980+42
| day7.clj   | 1815+60    | 2162+81    | 1227+48
| day8.clj   | 124+5      | 94+3       | 1177+62
| day9.clj   | 524+22     | 327+15     | 1227+50
| day11.clj  | 651+45     | 489+21     | 1287+47
| day17.clj  | 4633+228   | 1719+147   | 1556+149
| day19.clj  | 3256+252   | 3539+115   | 3063+272
| day24.clj  | 1846+42    | 3682+185   | 1615+79
```

**Comment by borkdude** [comment]
May be worth giving bb 1.0.167 a shot (just released). uclj inspired me to make a few optimizations in bb, thanks for this! When publishing benchmarks, I think it's good to mention also the version of uclj and bb used.

**Comment by erdos** [comment]
Hello @borkdude, thank you for your kind input. It's great to hear that you found inspiration in uclj. I do have to say that the team is doing an great job with bb. I have reviewed the recent versions and noticed significant enhancements, rendering the benchmarks obsolete. Therefore, I have decided to remove it entirely.
